name: 'Parse RSS feed'
description: 'Wait a designated number of milliseconds'
inputs:
  who-to-greet:  # rss
    description: 'who to greet'
    required: true
    default: 'greeting hello'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
